services:
  was1:
    build:
      context: ./was
      dockerfile: Dockerfile
    container_name: was
    ports:
      - "53000:53000"
    environment:
      - POSTGRES_HOST=postgres-defense
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_defense
    networks:
      - defense
    volumes:
      - ./was:/app
    working_dir: /app
    command: pnpm dev
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc: 65535

  postgres:
    image: postgres:latest
    container_name: postgres-defense
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_defense
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata_defense:/var/lib/postgresql/data
    networks:
      - defense
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g

  iperf3-server:
    image: networkstatic/iperf3
    container_name: iperf3-server
    command: -s
    ports:
      - "5201:5201"
    networks:
      - defense

networks:
  defense:
    driver: bridge

volumes:
  pgdata_defense: