services:
  was1:
    build:
      context: ./was1
      dockerfile: Dockerfile
    container_name: was1
    network_mode: "host"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=55432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_defense
      - PORT=53000
    volumes:
      - ./was1:/app
    working_dir: /app
    command: pnpm dev
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  was2:
    build:
      context: ./was2
      dockerfile: Dockerfile
    container_name: was2
    network_mode: "host"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=55432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_defense
      - PORT=53001
    volumes:
      - ./was2:/app
    working_dir: /app
    command: pnpm dev
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  postgres:
    image: postgres:latest
    container_name: postgres_defense
    command: postgres -p 55432 
    network_mode: "host"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_defense
    volumes:
      - ./was2/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata_defense:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    network_mode: "host"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  iperf3-server:
    image: networkstatic/iperf3
    container_name: iperf3-server
    command: -s
    network_mode: "host"

volumes:
  pgdata_defense: